flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    picture = FileField('picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = StringField('Comment', validators=[DataRequired()])
    submit1 = SubmitField('Submit')

class ReactForm(FlaskForm):
	submit2 = SubmitField('Upvote')

class DisReactForm(FlaskForm):
	submit3 = SubmitField('Down vote')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment , React
from flaskblog.posts.forms import PostForm, CommentForm, ReactForm, DisReactForm
from flaskblog.users.utils import save_post_picture

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_post_picture(form.picture.data)
            image_file = picture_file
            post = Post(title=form.title.data, content=form.content.data, author=current_user,post_file=image_file)
        else:
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    form = CommentForm()
    form2 = ReactForm()
    form3 = DisReactForm()
    reactis = React.query.filter_by(author3=current_user , author4=post).all()
    reactis2 = React.query.filter_by(author3=current_user , author4=post).first()
    postreactis = React.query.filter_by(author4=post).all()
    print(reactis2)
    comments = Comment.query.filter_by(post_id=post_id)\
        .order_by(Comment.date_comment.desc()).all()
    if form.submit1.data and form.validate():
        pos = Comment(comment_content=form.comment.data, author1=current_user,author2=post)
        db.session.add(pos)
        db.session.commit()
        flash('Thank you for the comment', 'success')
        return redirect(url_for('posts.post', post_id=post_id))
    if form2.submit2.data:
        rct = React(author3=current_user, author4=post)
        db.session.add(rct)
        db.session.commit()
        return redirect(url_for('posts.post', post_id=post_id))
    if form3.submit3.data:
        db.session.delete(reactis2)
        db.session.commit()
        return redirect(url_for('posts.post', post_id=post_id))

    return render_template('post.html', title=post.title, post=post,form=form,commentsno=len(comments),comments=comments,form3=form3, form2=form2,postreactis =len(postreactis),reactis=len(reactis))

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post, Comment
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password,birth_date=form.birth_date.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            print(picture_file)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
<iframe width="100%" height="315" src="https://www.youtube.com/embed/Sl48McISfnY?autoplay=1" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-4" data-aos="fade-right">
            <div class="section-title">
              <h2>Contact</h2>
              <p>For any query please leave a message we will contact you soon with your desired solution.</p>
            </div>
          </div>

          <div class="col-lg-8" data-aos="fade-up" data-aos-delay="100">
            <iframe style="border:0; width: 100%; height: 270px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d228.22163868917175!2d90.41306390000004!3d23.763556099999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755c7801aeeb41d%3A0x753bda7bc7ad5234!2sArif%20Store!5e0!3m2!1sen!2sbd!4v1610194182153!5m2!1sen!2sbd" frameborder="0" allowfullscreen></iframe>
            <div class="info mt-4">
              <i class="icofont-google-map"></i>
              <h4>Location:</h4>
              <p>30/1,Bagichertech, Wapda Road, West Rampura, Dhaka, BD</p>
            </div>
            <div class="row">
              <div class="col-lg-6 mt-4">
                <div class="info">
                  <i class="icofont-envelope"></i>
                  <h4>Email:</h4>
                  <p>ecoknowmebd@gmail.com</p>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="info w-100 mt-4">
                  <i class="icofont-phone"></i>
                  <h4>Call:</h4>
                  <p>+8801552350839</p>
                </div>
              </div>
            </div>
            <!-- FORM -->
            <form action="" method="post" role="form" class="php-email-form mt-4">
              {{ form.hidden_tag() }}
              <div class="form-row">
                <div class="col-md-6 form-group">
                  {{ form.name(class="form-control", id="name", placeholder="Your Name") }}
                  <!--input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validate"></div-->
                </div>
                <div class="col-md-6 form-group">
                  {% if form.email.errors %}
                    {{ form.email(class="form-control",id="email" ,placeholder="Your Email") }}
                    <div class="invalid-feedback">
                      {% for error in form.email.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class="form-control",id="email" ,placeholder="Your Email") }}
                  {% endif %}
                  <!--input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validate"></div-->
                </div>
              </div>
              <div class="form-group">
                {{ form.email(class="form-control" ,id="subject" ,placeholder="Subject") }}
                <!--input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                <div class="validate"></div-->
              </div>
              <div class="form-group">
                {{ form.message(class="form-control" ,placeholder="Message") }}
                <!--textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                <div class="validate"></div-->
              </div>
              <!--div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your message has been sent. Thank you!</div>
              </div-->
              <div class="form-group">
              {{ form.submit(style="background-color:#009970",class='btn btn-outline-info') }}
            </div>
            </form>
          </div>
        </div>

      </div>
    </section><!-- End Contact Section -->
{% endblock content %}

flaskblog/templates/brand.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.shortdis.label(class="form-control-label") }}
                {% if form.shortdis.errors %}
                    {{ form.shortdis(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.shortdis.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.shortdis(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(style="background-color:#009970",class="btn btn-outline-info") }}
        </div>
    </form>
{% endblock content %}

flaskblog/templates/catagory.html
{% extends "layout.html" %}
{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.shortdis.label(class="form-control-label") }}
                {% if form.shortdis.errors %}
                    {{ form.shortdis(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.shortdis.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.shortdis(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(style="background-color:#009970",class="btn btn-outline-info") }}
        </div>
    </form>
{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="card my-4">
    <h5 class="card-header">{{ legend }}</h5>
    <div class="card-body">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <!--legend style="text-align: middle;">Lets {{ legend }}</legend-->
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(style="background-color:#009970",class="btn btn-outline-info") }}
        </div>
    </form>
</div></div>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
<div class="col-md-8">
{% block content %}
    {% for post in posts.items %}
    <div class="card my-4">
          <h5 class="card-header"><a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">By {{ post.author.username }}</a></h5>
          <div class="card-body">
    <div class="container">
  <div class="well">
      <div class="media">
        <a class="pull-left" href="#">
          {% if post.post_file %}
        <img class="media-object" style="margin-right: 15px" width="150" height="150" src="{{ url_for('static', filename='post_pics/' + post.post_file) }}">
        {% endif %}
      </a>
      <div class="media-body">
        <h4 class="media-heading"><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
          <img class="d-flex mr-3 rounded-circle" width="50" height="50" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <p class="text-right"><!--a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">By {{ post.author.username }}</a--></p>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          <p>{{ post.content }}</p>
          <br><hr>
        </div></div>
          
       </div>
    </div>
  </div>
</div>
        <!--article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h4><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            <p class="article-content">{{ post.content }}</p>
            {% if post.post_file %}
            <img class="article-img" src="{{ url_for('static', filename='post_pics/' + post.post_file) }}">
            {% endif %}
          </div>
        </article-->
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-success mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-success mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}
</div>

flaskblog/templates/pdf.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Get pdf</title>
  </head>
  <body>
    <img height="50px" width="50px" src="https://i.ibb.co/9G4m4n1/20210103-151310.png">
  <h3>Invoice Voucher</h3>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <b style="float: right;">Inoice: {{orders.invoice}} </b> 
            <br>
            Status: {{orders.status}}
            <br>
            Customer name: {{customer.username}}
            <br>
            Customer email: {{customer.email}}
            <br>
            Customer contact: 01xxxxxxxxx
            <br>
            <br>
        <table class="table table-sm">
            <thead>
                <th>Sr</th>
                <th>Name</th>
                <th>Color</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Discount</th>
                <th>Subtotal</th>
            </thead>
            <tbody>
                {% for key, product in orders.orders.items() %}
                {% set discount =(product.discount|float/100) * product.price|float %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>{{product.name}}</td>
                    <form action="{{url_for('main.updatecart', code=key)}}" method="post">
                    <td> 
                        {{product.color|capitalize}}
                    </td>
                    <td>${{"%.2f"|format(product.price)}}</td>
                    <td> {{product.quantity}} </td>
                    {% if product.discount  %}
                    <td>{{product.discount}} % &nbsp; &nbsp; is {{"%.2f"|format(discount)}}</td>
                    {% else %}
                    <td></td>
                    {% endif %}
                    {% set subtotal = product.quantity|int * product.price|float  %}
                    <td>${{"%.2f"|format(subtotal - discount|round(1,'floor')) }}</td>
                </form>        
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <table class="table table-sm">
           <tr>
               <td width="35%"></td>
               <td> <h5>Tax: ${{tax}}</h5></td>
               <td> <h5>Grand total: ${{grandTotal}}</h3> </td>
        
           </tr>
        </table>
    </div>
  </div>
</div>
   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
    <div class="card my-4">
    <h5 class="card-header"></h5>
    <div class="card-body">
  <article class="media content-section">
    <img class="d-flex mr-3 rounded-circle" width="100" height="100" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <div class="col-lg-8">
        <!--post collumn-->
      <h2 class="article-title">{{ post.title }}</h2>
       {% if post.post_file %}
            <img class="img-fluid rounded" width="900" height="300" src="{{ url_for('static', filename='post_pics/' + post.post_file) }}">
        {% endif %}
      <p class="article-content lead">{{ post.content }}</p>
      <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
      <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
       <div class="form-group">
                    {{ form.comment.label(class="form-control-label") }}
                    {% if form.comment.errors %}
                        {{ form.comment(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.comment.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.comment(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                {{ form.submit1(class="btn btn-success") }}
                <i class="fas fa-comments"><p>({{commentsno}})</p></i>
            </div>
        </form>
        <form method="POST" action="">
        {% if reactis == 0 %}
          <div class="form-group">
              {{ form2.submit2(class="btn btn-success mb-2") }}
              <i class="fas fa-heart"><p>({{ postreactis }})</p></i>
          </div>
        {% endif %}
        </form>
        <form method="POST" action="">
        {% if reactis != 0 %}
          <div class="form-group">
              {{ form3.submit3(class="btn btn-outline-info mb-2") }}
              <i class="fas fa-thumbs-down"><p>({{ postreactis }})</p></i>
          </div>
        {% endif %}
        </form>
      </div></div>
        {{ share.load() }}
        {{ share.create(title="Share with:  ")}}
      <!--comment-->
      <div class="card my-4">
          <h5 class="card-header">Comment</h5>
          <div class="card-body">
    {% for comment in comments %}
        <article class="media content-section">
          <img class="d-flex mr-3 rounded-circle" width="50" height="50" src="{{ url_for('static', filename='profile_pics/' + comment.author1.image_file) }}">
          <!--h4 class="mb-3"> {{ comment.author1.username[:5] }}</h4-->
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ comment.author1.username }}</a>
              <small class="text-muted">{{ comment.date_comment.strftime('%Y-%m-%d, %H:%M:%S') }}</small>
            </div>
            <p class="article-content">{{ comment.comment_content }}</p>
          </div>
        </article>
    {% endfor %}
  </div></div>
      <!--comment-->
           </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div></div>
{% endblock content %}